**Data cleaning and transformation**

In [162]:
import pandas as pd
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/python dataset.xlsx")

select one colomn

In [163]:
data["Gender"]

0      Female
1      Female
2      Female
3      Female
4        Male
        ...
295    Female
296    Female
297      Male
298    Female
299      Male
Name: Gender, Length: 300, dtype: object

selecting multible colomn

In [164]:
data[['Program','Gender']]

                     Program  Gender
0           Computer Science  Female
1              Public Health  Female
2    Business Administration  Female
3           Computer Science  Female
4                Engineering    Male
..                       ...     ...
295             Data Science  Female
296         Computer Science  Female
297                Economics    Male
298  Business Administration  Female
299            Public Health    Male

[300 rows x 2 columns]

**selecting rows**

selecting  rows using loc[]

In [165]:
data.loc[0:5]

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
0,ENR0123,Female,Computer Science,2026-01-06 00:00:00,Full-Time,1037.53,Graduated
1,ENR0050,Female,Public Health,2026-05-02 00:00:00,Full-Time,NaN,Graduated
2,ENR0241,Female,Business Administration,2026-05-19 00:00:00,NaN,823.61,Graduated
3,ENR0279,Female,Computer Science,2025-06-21 00:00:00,Full-Time,998.42,Graduated
4,ENR0091,Male,Engineering,2025-10-03 00:00:00,Online,1358.18,NaN
5,ENR0166,Female,Business Administration,2025-06-18 00:00:00,Online,761.3,Withdrawn

selecting rows and columns using loc[]

In [166]:
data.loc[0:5,['Program','Gender']]

                   Program  Gender
0         Computer Science  Female
1            Public Health  Female
2  Business Administration  Female
3         Computer Science  Female
4              Engineering    Male
5  Business Administration  Female

selecting rows and columns using iloc[]

In [167]:
data.iloc[0:3]

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
0,ENR0123,Female,Computer Science,2026-01-06 00:00:00,Full-Time,1037.53,Graduated
1,ENR0050,Female,Public Health,2026-05-02 00:00:00,Full-Time,NaN,Graduated
2,ENR0241,Female,Business Administration,2026-05-19 00:00:00,NaN,823.61,Graduated

**Filtering** **data**

Numerical filtering

In [168]:
# Convert Tuition_Fee to numeric, coercing non-numeric string values to NaN
data['Tuition_Fee'] = pd.to_numeric(data['Tuition_Fee'], errors='coerce')

In [169]:
# Now filter the DataFrame
data[data['Tuition_Fee'] < 10]

Empty DataFrame
Columns: [Student_ID, Gender, Program, Enrollment_Date, Study_Mode, Tuition_Fee, Enrollment_Status]
Index: []

categorical filtering

In [170]:
data[data['Gender']=='Female']

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
0,ENR0123,Female,Computer Science,2026-01-06 00:00:00,Full-Time,1037.53,Graduated
1,ENR0050,Female,Public Health,2026-05-02 00:00:00,Full-Time,NaN,Graduated
2,ENR0241,Female,Business Administration,2026-05-19 00:00:00,NaN,823.61,Graduated
3,ENR0279,Female,Computer Science,2025-06-21 00:00:00,Full-Time,998.42,Graduated
5,ENR0166,Female,Business Administration,2025-06-18 00:00:00,Online,761.30,Withdrawn
...,...,...,...,...,...,...,...
292,ENR0189,Female,Computer Science,2025-12-02 00:00:00,Full-Time,974.48,Active
293,ENR0147,Female,Computer Science,2025-05-14 00:00:00,Full-Time,962.27,NaN
295,ENR0110,Female,Data Science,2026-03-12 00:00:00,Full-Time,1235.12,Active
296,ENR0246,Female,Computer Science,2025-06-13 00:00:00,Online,1014.19,Active
298,ENR0227,Female,Business Administration,2025-11-13 00:00:00,Part-Time,905.56,Deferred

Filtering Multiple Categories

In [171]:

data[data['Gender'].isin(['Female','NAN'])]

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
0,ENR0123,Female,Computer Science,2026-01-06 00:00:00,Full-Time,1037.53,Graduated
1,ENR0050,Female,Public Health,2026-05-02 00:00:00,Full-Time,NaN,Graduated
2,ENR0241,Female,Business Administration,2026-05-19 00:00:00,NaN,823.61,Graduated
3,ENR0279,Female,Computer Science,2025-06-21 00:00:00,Full-Time,998.42,Graduated
5,ENR0166,Female,Business Administration,2025-06-18 00:00:00,Online,761.30,Withdrawn
...,...,...,...,...,...,...,...
292,ENR0189,Female,Computer Science,2025-12-02 00:00:00,Full-Time,974.48,Active
293,ENR0147,Female,Computer Science,2025-05-14 00:00:00,Full-Time,962.27,NaN
295,ENR0110,Female,Data Science,2026-03-12 00:00:00,Full-Time,1235.12,Active
296,ENR0246,Female,Computer Science,2025-06-13 00:00:00,Online,1014.19,Active
298,ENR0227,Female,Business Administration,2025-11-13 00:00:00,Part-Time,905.56,Deferred

Multiple Conditions

In [172]:
data[ (data['Gender']=='Female') & (data['Tuition_Fee']< 20) ]

Empty DataFrame
Columns: [Student_ID, Gender, Program, Enrollment_Date, Study_Mode, Tuition_Fee, Enrollment_Status]
Index: []

Sorting Data

In [173]:
data.sort_values('Tuition_Fee')

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
191,ENR0211,Female,Economics,2025-07-31 00:00:00,Full-Time,709.26,Graduated
119,ENR0122,Male,Economics,NaN,Online,717.16,Active
253,ENR0088,Male,Business Administration,2025-07-16 00:00:00,Online,720.20,NaN
106,ENR0265,Female,NaN,2025-07-30 00:00:00,Full-Time,720.97,Active
121,ENR0178,Male,Business Administration,2025-06-05 00:00:00,NaN,729.70,Active
...,...,...,...,...,...,...,...
204,ENR0026,Female,Data Science,2025-08-18 00:00:00,Full-Time,NaN,Active
208,ENR0209,Male,Computer Science,2025-10-19 00:00:00,Full-Time,NaN,Graduated
231,ENR0267,Female,Economics,2025-10-03 00:00:00,Online,NaN,Active
237,ENR0132,Female,Computer Science,2025-08-09 00:00:00,Full-Time,NaN,Withdrawn
264,ENR0053,Female,Data Science,2025-09-03 00:00:00,Full-Time,NaN,Graduated

In [174]:
data.sort_values('Tuition_Fee',ascending=True)

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
191,ENR0211,Female,Economics,2025-07-31 00:00:00,Full-Time,709.26,Graduated
119,ENR0122,Male,Economics,NaN,Online,717.16,Active
253,ENR0088,Male,Business Administration,2025-07-16 00:00:00,Online,720.20,NaN
106,ENR0265,Female,NaN,2025-07-30 00:00:00,Full-Time,720.97,Active
121,ENR0178,Male,Business Administration,2025-06-05 00:00:00,NaN,729.70,Active
...,...,...,...,...,...,...,...
204,ENR0026,Female,Data Science,2025-08-18 00:00:00,Full-Time,NaN,Active
208,ENR0209,Male,Computer Science,2025-10-19 00:00:00,Full-Time,NaN,Graduated
231,ENR0267,Female,Economics,2025-10-03 00:00:00,Online,NaN,Active
237,ENR0132,Female,Computer Science,2025-08-09 00:00:00,Full-Time,NaN,Withdrawn
264,ENR0053,Female,Data Science,2025-09-03 00:00:00,Full-Time,NaN,Graduated

Descending Order

In [175]:
data.sort_values('Tuition_Fee',ascending=False)

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
99,ENR0258,Female,NaN,2025-05-09 00:00:00,Full-Time,1379.03,Active
284,ENR0255,Male,Engineering,2025-11-01 00:00:00,Full-Time,1374.35,NaN
4,ENR0091,Male,Engineering,2025-10-03 00:00:00,Online,1358.18,NaN
141,ENR0223,Female,Engineering,2025-07-18 00:00:00,NaN,1357.89,Graduated
147,ENR0044,Male,Engineering,2026-07-06 00:00:00,Part-Time,1354.04,Deferred
...,...,...,...,...,...,...,...
204,ENR0026,Female,Data Science,2025-08-18 00:00:00,Full-Time,NaN,Active
208,ENR0209,Male,Computer Science,2025-10-19 00:00:00,Full-Time,NaN,Graduated
231,ENR0267,Female,Economics,2025-10-03 00:00:00,Online,NaN,Active
237,ENR0132,Female,Computer Science,2025-08-09 00:00:00,Full-Time,NaN,Withdrawn
264,ENR0053,Female,Data Science,2025-09-03 00:00:00,Full-Time,NaN,Graduated

Sorting by Multiple Columns

In [176]:
data.sort_values(by=['Enrollment_Status','Study_Mode'])

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
13,ENR0222,Male,Data Science,2025-03-08 00:00:00,Part-Time,1039.18,ACTIVE
133,ENR0225,Male,Data Science,2025-12-21 00:00:00,FULL-TIME,1069.75,Active
7,ENR0093,Male,Public Health,2026-06-26 00:00:00,Full-Time,968.97,Active
8,ENR0108,Female,Public Health,2026-04-23 00:00:00,Full-Time,815.31,Active
9,ENR0106,Male,Economics,2025-07-31 00:00:00,Full-Time,866.46,Active
...,...,...,...,...,...,...,...
277,ENR0046,Female,Engineering,2025-05-01 00:00:00,Online,1208.64,NaN
61,ENR0097,Female,Data Science,2026-04-03 00:00:00,Part-Time,990.07,NaN
190,ENR0244,Female,Business Administration,2026-04-14 00:00:00,Part-Time,835.71,NaN
202,ENR0264,Male,Data Science,2025-04-18 00:00:00,Part-Time,1064.78,NaN
101,ENR0037,Female,Business Administration,2025-12-02 00:00:00,NaN,866.74,NaN

In [177]:
data.sort_values(by=['Enrollment_Status','Study_Mode'],ascending=[True,False])

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
13,ENR0222,Male,Data Science,2025-03-08 00:00:00,Part-Time,1039.18,ACTIVE
281,ENR0220,Female,Engineering,2025-09-17 00:00:00,online,1178.08,Active
138,ENR0103,Female,Engineering,2026-03-01 00:00:00,full-time,1222.31,Active
155,ENR0005,Female,Computer Science,2025-12-19 00:00:00,full-time,1035.39,Active
14,ENR0125,Male,Business Administration,2025-08-03 00:00:00,Part-Time,808.90,Active
...,...,...,...,...,...,...,...
102,ENR0001,Male,Computer Science,2025-12-03 00:00:00,Full-Time,927.99,NaN
118,ENR0035,Male,Public Health,2025-05-27 00:00:00,Full-Time,972.65,NaN
284,ENR0255,Male,Engineering,2025-11-01 00:00:00,Full-Time,1374.35,NaN
293,ENR0147,Female,Computer Science,2025-05-14 00:00:00,Full-Time,962.27,NaN
101,ENR0037,Female,Business Administration,2025-12-02 00:00:00,NaN,866.74,NaN